version: '3.9'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379/0
      TASK_LOG_DIR: /app/task_logs
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4.1-mini}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-changeme}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
    ports:
      - "8000:8000"
    volumes:
      - backend-logs:/app/task_logs
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:8000}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  redis-data:
  backend-logs:
