version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL:-sqlite:////app/data/automation.db}
      REPORT_ROOT: /app/reports
      DEFAULT_EXECUTOR: ${DEFAULT_EXECUTOR:-automation-bot}
      STEP_DELAY_SECONDS: ${STEP_DELAY_SECONDS:-0.6}
    volumes:
      - backend-data:/app/data
      - backend-reports:/app/reports
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:8000}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend-data:
  backend-reports:
